import { StyleSheet } from 'react-native';


const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFDAF7',
    },
    titleContainer: {
        backgroundColor: '#FFEB3B',
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 30,
        marginBottom: 40,
        borderWidth: 3,
        borderColor: '#FF6347',
    },
    title: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#FF6347',
        textAlign: 'center',
        fontFamily: 'Comic Sans MS',
        textShadowColor: '#FFF',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 10,
    },
    numberText: {
        fontSize: 120,
        fontWeight: 'bold',
        color: '#FF6347',
        textShadowColor: '#FFF',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 10,
    },
    numberEnText: {
        fontSize: 26,
        fontWeight: 'bold',
        color: '#FF6347',
        marginBottom: 40,
        textShadowColor: '#FFF',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 10,
    },
    button: {
        backgroundColor: '#FF69B4',
        paddingVertical: 20,
        paddingHorizontal: 50,
        borderRadius: 50,
        marginBottom: 40,
        elevation: 10,
        shadowColor: '#FF1493',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
    },
    buttonText: {
        color: '#FFF',
        fontSize: 22,
        fontWeight: 'bold',
        textAlign: 'center',
        textTransform: 'uppercase',
        fontFamily: 'Comic Sans MS',
    },
    iconButton: {
        backgroundColor: '#FFD700',
        borderRadius: 50,
        padding: 20,
        marginBottom: 40,
        elevation: 5,
        shadowColor: '#FFD700',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    iconButton: {
        marginBottom: 20,
        padding: 10,
        backgroundColor: '#FF4500',
        borderRadius: 50,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 5,
    },
    footer: {
        position: 'absolute',
        bottom: 20,
        fontSize: 16,
        color: '#8A2BE2',
        fontWeight: 'bold',
        fontStyle: 'italic',
    },
});

export default styles;